### PR TITLE
Add option to disable show/hide behavior

### PR DESCRIPTION
**Pull request by bfncs**
Allows handling showing and hiding of the menu versions independently of the plugin, e.g. with media queries.

### CODE REVIEW

**Comment by micc83** [comment]
Hello @bfncs ,
Thank you for you PR. I haven't looked at ReSmenu in a while but giving a look at your code the first thing that comes to my eyes is that you're creating the responsive menu (then hiding it) even when the screen size is greater than the one specified. My implementation was uglier but it created the select list only at need in order to do not clutter up the loading of the page. Could you review your code with that in mind?

**Comment by bfncs** [comment]
Hi @micc83,

thanks for your quick feedback.

You are right for sure about cluttering up the DOM sometimes unncessarily. On the other hand if the select DOM elements aren't created on initialization, there would still be a need to constantly check if the creation is necessary on each triggering of the `window.resize` event, defeating the purpose of this patch overall.

Maybe there should be an extra option for this? Or a dependency on a a debounced resize library like [louisremi/jquery-smartresize](https://github.com/louisremi/jquery-smartresize).

**Comment by micc83** [comment]
Well, even though window.resize is mostly fired by people testing the plugin more than the actual website visitors adding debouncing has been in my priority list for the next ResMenu release for a while (no need to add a dependency for that, it's a pretty short snippet) but unfortunately I'm to busy to implement it right now. But yes, that would be the perfect solution :)

**Comment by bfncs** [comment]
Thanks a lot for your comments.

Well, I think in this case it would be the best to close this pull request in favor of a better implementation in the next release. Agreed?

**Comment by micc83** [comment]
Cool with it but I'd ask you to do not close the PR, I'll keep it as a
reminder and merge it to a new dev branch for v1.0.0. Thank you again for
your interest in the project.

2015-10-23 12:51 GMT+02:00 Marc Löhe <notifications@github.com>:

> Thanks a lot for your comments.
>
> Well, I think in this case it would be the best to close this pull request
> in favor of a better implementation in the next release. Agreed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/micc83/ReSmenu/pull/7#issuecomment-150542140>.
>



-- 
*Alessandro Benoit*
Cel: +39 392 0078370
Email: micc83@gmail.com

**Comment by bfncs** [comment]
Sure, that sounds like a good idea. Keep up the good work.

**Pull request closed without merging**
